name: Deploy Distribution
# on: [push,workflow_dispatch
on:
    push:
        branches:
            - main
            - feature/*
        paths-ignore:
            - 'README.md'
            - 'docs/**'
            - '.github/**'
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v7
        # run: |
        #   echo "Cloning the repository..."
        #   echo "${{toJson(github)}}"
        #   echo "${{toJson(github.repository)}}"
        #   git clone https://github.com/${{github.repository}}.git
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    #   - name: Print Node.js version
    #     run: node -v
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests 
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build the distribution
        run: npm run build
      - name: Deploy to GitHub Pages
        run: echo "Deploy successful..."